### ISSUE TITLE
Discrepancy between mypy pre-commit and CI

### ISSUE THREAD

**Issue by ReinderVosDeWael** [childmindresearch/template-python-repository#12]
Our mypy pre-commit excludes the `tests` directory, whereas our CI includes it. This can lead to failing CI even though this should've been caught by the `pre-commit` hook.

The fix is simple, but what behavior do we want? Include `tests` in the pre-commit hook (my preferred option) or exclude `tests` in the CI?

**Comment by nx10** [comment]
My vote is include I don't see a reason why not.
